### PR TITLE
Scripts dir

### PR DESCRIPTION
**Pull request by olliethomas**
Add a place for scripts that are (possibly) useful.

### CODE REVIEW

**Comment by olliethomas** [comment]
This is perhaps only useful, if you have conda installed on your machine :/

**Comment by robinjam** [comment]
I think I'd probably put this in a wiki page, what do you reckon?

And I'd maybe also add that you can install GDAL through Homebrew or Apt if (like me 😅) you don't have Conda

**Comment by olliethomas** [comment]
there's a homebrew/apt installation? I don't see that?

**Comment by robinjam** [comment]
Yep, `brew install gdal` or `apt install gdal-bin`

(I looked into this before, because I wanted to merge the tile conversion stuff into the web app, and GDAL comes with a script for doing just that 😄)

**Comment by olliethomas** [comment]
Closing in favour of a wiki page.

**Pull request closed without merging**
